# Generated by Django 5.2.6 on 2025-09-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('PD', 'Paid')], default='P', max_length=2),
        ),
    ]
