# Generated by Django 5.2.6 on 2025-09-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='nhif',
            new_name='sha',
        ),
    ]
