# Generated by Django 5.2.6 on 2025-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_payroll_employee_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
