# Generated by Django 5.2.6 on 2025-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_balance',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
