# Generated by Django 6.0.3 on 2026-09-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_employee_annual_leave_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
